# Generated by Django 4.2 on 2025-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('surname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('edat', models.DateField(max_length=500)),
                ('genere', models.CharField(max_length=500)),
                ('curs', models.CharField(max_length=500)),
                ('tutor', models.CharField(max_length=500)),
                ('moduls', models.CharField(max_length=500)),

            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('surname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('edat', models.DateField(max_length=500)),
                ('genere', models.CharField(max_length=500)),
                ('curs', models.CharField(max_length=500)),
                ('tutor', models.CharField(max_length=500)),
                ('moduls', models.CharField(max_length=500)),
            ],
        ),
    ]
